version: '3.9'

services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/instance
    environment:
      - FLASK_ENV=production
    restart: always
